# Generated by Django 3.2.3 on 2021-06-23 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('ERROR', 'error'), ("('SUCCESS', 'success')", 'Success'), ("('WARNING', 'warning')", 'Warning'), ('INFO', 'info')], default='INFO', max_length=22)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('S', 'sent'), ('D', 'delivered'), ('R', 'read')], default='S', max_length=10)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='nodes.node')),
            ],
        ),
    ]
