# Generated by Django 3.2.5 on 2021-07-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='address',
        ),
        migrations.RemoveField(
            model_name='node',
            name='city',
        ),
        migrations.RemoveField(
            model_name='node',
            name='country',
        ),
        migrations.RemoveField(
            model_name='node',
            name='phone',
        ),
    ]
